# Generated by Django 4.2.1 on 2025-05-20 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('code', models.IntegerField(max_length=100, verbose_name='Код категории')),
                ('parent_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lookup.category', verbose_name='Родительская категория')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название материала')),
                ('code', models.IntegerField(max_length=100, verbose_name='Код материала')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена материала')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marerials', to='lookup.category', verbose_name='Категория материала')),
            ],
        ),
    ]
