# Generated by Django 4.2.1 on 2025-05-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_rename_materials_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.IntegerField(verbose_name='Код категории'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lookup.category', verbose_name='Категория материала'),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.IntegerField(verbose_name='Код материала'),
        ),
    ]
